// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="vector_scalar_sum_vector_scalar_sum,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu9eg-ffvb1156-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=268435474,HLS_SYN_TPT=none,HLS_SYN_MEM=8,HLS_SYN_DSP=0,HLS_SYN_FF=2331,HLS_SYN_LUT=3156,HLS_VERSION=2025_1}" *)

module vector_scalar_sum (
        ap_clk,
        ap_rst_n,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 16'd1;
parameter    ap_ST_fsm_state2 = 16'd2;
parameter    ap_ST_fsm_state3 = 16'd4;
parameter    ap_ST_fsm_state4 = 16'd8;
parameter    ap_ST_fsm_state5 = 16'd16;
parameter    ap_ST_fsm_state6 = 16'd32;
parameter    ap_ST_fsm_state7 = 16'd64;
parameter    ap_ST_fsm_state8 = 16'd128;
parameter    ap_ST_fsm_state9 = 16'd256;
parameter    ap_ST_fsm_state10 = 16'd512;
parameter    ap_ST_fsm_state11 = 16'd1024;
parameter    ap_ST_fsm_state12 = 16'd2048;
parameter    ap_ST_fsm_state13 = 16'd4096;
parameter    ap_ST_fsm_state14 = 16'd8192;
parameter    ap_ST_fsm_state15 = 16'd16384;
parameter    ap_ST_fsm_state16 = 16'd32768;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM0_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM0_DATA_WIDTH = 128;
parameter    C_M_AXI_GMEM0_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_USER_VALUE = 0;
parameter    C_M_AXI_GMEM0_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM0_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM1_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM1_DATA_WIDTH = 128;
parameter    C_M_AXI_GMEM1_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_USER_VALUE = 0;
parameter    C_M_AXI_GMEM1_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM1_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM0_WSTRB_WIDTH = (128 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM1_WSTRB_WIDTH = (128 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_AWADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_AWID;
output  [7:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [C_M_AXI_GMEM0_AWUSER_WIDTH - 1:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_WDATA;
output  [C_M_AXI_GMEM0_WSTRB_WIDTH - 1:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_WID;
output  [C_M_AXI_GMEM0_WUSER_WIDTH - 1:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_ARADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_ARID;
output  [7:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [C_M_AXI_GMEM0_ARUSER_WIDTH - 1:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_RID;
input  [C_M_AXI_GMEM0_RUSER_WIDTH - 1:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_BID;
input  [C_M_AXI_GMEM0_BUSER_WIDTH - 1:0] m_axi_gmem0_BUSER;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_AWADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_AWID;
output  [7:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [C_M_AXI_GMEM1_AWUSER_WIDTH - 1:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_WDATA;
output  [C_M_AXI_GMEM1_WSTRB_WIDTH - 1:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_WID;
output  [C_M_AXI_GMEM1_WUSER_WIDTH - 1:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_ARADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_ARID;
output  [7:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [C_M_AXI_GMEM1_ARUSER_WIDTH - 1:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_RID;
input  [C_M_AXI_GMEM1_RUSER_WIDTH - 1:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_BID;
input  [C_M_AXI_GMEM1_BUSER_WIDTH - 1:0] m_axi_gmem1_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [15:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] input_vector;
wire   [63:0] output_vector;
wire   [31:0] scalar;
wire   [31:0] size;
reg    gmem0_blk_n_AR;
wire    ap_CS_fsm_state2;
reg    gmem1_blk_n_AW;
wire    ap_CS_fsm_state9;
reg    gmem1_blk_n_B;
wire    ap_CS_fsm_state16;
reg   [31:0] size_read_reg_266;
reg   [31:0] scalar_read_reg_271;
wire   [30:0] num_transfers_fu_196_p3;
reg   [30:0] num_transfers_reg_276;
reg   [59:0] trunc_ln1_reg_281;
wire   [30:0] empty_fu_220_p3;
reg   [30:0] empty_reg_287;
reg   [59:0] trunc_ln38_1_reg_292;
wire   [63:0] zext_ln38_fu_251_p1;
reg   [63:0] zext_ln38_reg_303;
wire    grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_ap_start;
wire    grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_ap_done;
wire    grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_ap_idle;
wire    grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_ap_ready;
wire    grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_AWVALID;
wire   [63:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_AWADDR;
wire   [0:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_AWID;
wire   [31:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_AWLEN;
wire   [2:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_AWSIZE;
wire   [1:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_AWBURST;
wire   [1:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_AWLOCK;
wire   [3:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_AWCACHE;
wire   [2:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_AWPROT;
wire   [3:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_AWQOS;
wire   [3:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_AWREGION;
wire   [0:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_AWUSER;
wire    grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_WVALID;
wire   [127:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_WDATA;
wire   [15:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_WSTRB;
wire    grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_WLAST;
wire   [0:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_WID;
wire   [0:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_WUSER;
wire    grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_ARVALID;
wire   [63:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_ARADDR;
wire   [0:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_ARID;
wire   [31:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_ARLEN;
wire   [2:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_ARSIZE;
wire   [1:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_ARBURST;
wire   [1:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_ARLOCK;
wire   [3:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_ARCACHE;
wire   [2:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_ARPROT;
wire   [3:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_ARQOS;
wire   [3:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_ARREGION;
wire   [0:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_ARUSER;
wire    grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_RREADY;
wire    grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_BREADY;
wire    grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_AWVALID;
wire   [63:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_AWADDR;
wire   [0:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_AWID;
wire   [31:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_AWLEN;
wire   [2:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_AWSIZE;
wire   [1:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_AWBURST;
wire   [1:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_AWLOCK;
wire   [3:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_AWCACHE;
wire   [2:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_AWPROT;
wire   [3:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_AWQOS;
wire   [3:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_AWREGION;
wire   [0:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_AWUSER;
wire    grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_WVALID;
wire   [127:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_WDATA;
wire   [15:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_WSTRB;
wire    grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_WLAST;
wire   [0:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_WID;
wire   [0:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_WUSER;
wire    grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_ARVALID;
wire   [63:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_ARADDR;
wire   [0:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_ARID;
wire   [31:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_ARLEN;
wire   [2:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_ARSIZE;
wire   [1:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_ARBURST;
wire   [1:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_ARLOCK;
wire   [3:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_ARCACHE;
wire   [2:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_ARPROT;
wire   [3:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_ARQOS;
wire   [3:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_ARREGION;
wire   [0:0] grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_ARUSER;
wire    grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_RREADY;
wire    grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_BREADY;
wire    gmem0_0_AWREADY;
wire    gmem0_0_WREADY;
reg    gmem0_0_ARVALID;
wire    gmem0_0_ARREADY;
reg   [63:0] gmem0_0_ARADDR;
reg   [31:0] gmem0_0_ARLEN;
wire    gmem0_0_RVALID;
reg    gmem0_0_RREADY;
wire   [127:0] gmem0_0_RDATA;
wire   [8:0] gmem0_0_RFIFONUM;
wire    gmem0_0_BVALID;
reg    gmem1_0_AWVALID;
wire    gmem1_0_AWREADY;
reg   [63:0] gmem1_0_AWADDR;
reg   [31:0] gmem1_0_AWLEN;
reg    gmem1_0_WVALID;
wire    gmem1_0_WREADY;
wire    gmem1_0_ARREADY;
wire    gmem1_0_RVALID;
wire   [127:0] gmem1_0_RDATA;
wire   [8:0] gmem1_0_RFIFONUM;
wire    gmem1_0_BVALID;
reg    gmem1_0_BREADY;
reg    grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_ap_start_reg;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
wire  signed [63:0] sext_ln38_fu_238_p1;
wire  signed [63:0] sext_ln38_2_fu_256_p1;
wire   [31:0] add_ln35_fu_142_p2;
wire   [31:0] sub_ln35_fu_156_p2;
wire   [29:0] tmp_fu_162_p4;
wire   [30:0] zext_ln35_fu_172_p1;
wire   [29:0] tmp_1_fu_182_p4;
wire   [0:0] tmp_2_fu_148_p3;
wire   [30:0] sub_ln35_1_fu_176_p2;
wire   [30:0] zext_ln35_1_fu_192_p1;
wire   [0:0] icmp_ln38_fu_204_p2;
wire  signed [31:0] sext_ln38_1_fu_248_p1;
reg   [15:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
reg    ap_ST_fsm_state16_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 16'd1;
#0 grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_ap_start_reg = 1'b0;
end

vector_scalar_sum_vector_scalar_sum_Pipeline_PROCESS_LOOP grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_ap_start),
    .ap_done(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_ap_done),
    .ap_idle(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_ap_idle),
    .ap_ready(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_ap_ready),
    .m_axi_gmem0_0_AWVALID(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_AWVALID),
    .m_axi_gmem0_0_AWREADY(1'b0),
    .m_axi_gmem0_0_AWADDR(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_AWADDR),
    .m_axi_gmem0_0_AWID(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_AWID),
    .m_axi_gmem0_0_AWLEN(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_AWLEN),
    .m_axi_gmem0_0_AWSIZE(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_AWSIZE),
    .m_axi_gmem0_0_AWBURST(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_AWBURST),
    .m_axi_gmem0_0_AWLOCK(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_AWLOCK),
    .m_axi_gmem0_0_AWCACHE(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_AWCACHE),
    .m_axi_gmem0_0_AWPROT(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_AWPROT),
    .m_axi_gmem0_0_AWQOS(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_AWQOS),
    .m_axi_gmem0_0_AWREGION(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_AWREGION),
    .m_axi_gmem0_0_AWUSER(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_AWUSER),
    .m_axi_gmem0_0_WVALID(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_WVALID),
    .m_axi_gmem0_0_WREADY(1'b0),
    .m_axi_gmem0_0_WDATA(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_WDATA),
    .m_axi_gmem0_0_WSTRB(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_WSTRB),
    .m_axi_gmem0_0_WLAST(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_WLAST),
    .m_axi_gmem0_0_WID(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_WID),
    .m_axi_gmem0_0_WUSER(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_WUSER),
    .m_axi_gmem0_0_ARVALID(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_ARVALID),
    .m_axi_gmem0_0_ARREADY(gmem0_0_ARREADY),
    .m_axi_gmem0_0_ARADDR(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_ARADDR),
    .m_axi_gmem0_0_ARID(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_ARID),
    .m_axi_gmem0_0_ARLEN(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_ARLEN),
    .m_axi_gmem0_0_ARSIZE(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_ARSIZE),
    .m_axi_gmem0_0_ARBURST(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_ARBURST),
    .m_axi_gmem0_0_ARLOCK(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_ARLOCK),
    .m_axi_gmem0_0_ARCACHE(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_ARCACHE),
    .m_axi_gmem0_0_ARPROT(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_ARPROT),
    .m_axi_gmem0_0_ARQOS(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_ARQOS),
    .m_axi_gmem0_0_ARREGION(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_ARREGION),
    .m_axi_gmem0_0_ARUSER(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_ARUSER),
    .m_axi_gmem0_0_RVALID(gmem0_0_RVALID),
    .m_axi_gmem0_0_RREADY(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_RREADY),
    .m_axi_gmem0_0_RDATA(gmem0_0_RDATA),
    .m_axi_gmem0_0_RLAST(1'b0),
    .m_axi_gmem0_0_RID(1'd0),
    .m_axi_gmem0_0_RFIFONUM(gmem0_0_RFIFONUM),
    .m_axi_gmem0_0_RUSER(1'd0),
    .m_axi_gmem0_0_RRESP(2'd0),
    .m_axi_gmem0_0_BVALID(1'b0),
    .m_axi_gmem0_0_BREADY(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_BREADY),
    .m_axi_gmem0_0_BRESP(2'd0),
    .m_axi_gmem0_0_BID(1'd0),
    .m_axi_gmem0_0_BUSER(1'd0),
    .m_axi_gmem1_0_AWVALID(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_AWVALID),
    .m_axi_gmem1_0_AWREADY(gmem1_0_AWREADY),
    .m_axi_gmem1_0_AWADDR(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_AWADDR),
    .m_axi_gmem1_0_AWID(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_AWID),
    .m_axi_gmem1_0_AWLEN(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_AWLEN),
    .m_axi_gmem1_0_AWSIZE(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_AWSIZE),
    .m_axi_gmem1_0_AWBURST(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_AWBURST),
    .m_axi_gmem1_0_AWLOCK(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_AWLOCK),
    .m_axi_gmem1_0_AWCACHE(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_AWCACHE),
    .m_axi_gmem1_0_AWPROT(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_AWPROT),
    .m_axi_gmem1_0_AWQOS(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_AWQOS),
    .m_axi_gmem1_0_AWREGION(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_AWREGION),
    .m_axi_gmem1_0_AWUSER(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_AWUSER),
    .m_axi_gmem1_0_WVALID(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_WVALID),
    .m_axi_gmem1_0_WREADY(gmem1_0_WREADY),
    .m_axi_gmem1_0_WDATA(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_WDATA),
    .m_axi_gmem1_0_WSTRB(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_WSTRB),
    .m_axi_gmem1_0_WLAST(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_WLAST),
    .m_axi_gmem1_0_WID(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_WID),
    .m_axi_gmem1_0_WUSER(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_WUSER),
    .m_axi_gmem1_0_ARVALID(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_ARVALID),
    .m_axi_gmem1_0_ARREADY(1'b0),
    .m_axi_gmem1_0_ARADDR(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_ARADDR),
    .m_axi_gmem1_0_ARID(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_ARID),
    .m_axi_gmem1_0_ARLEN(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_ARLEN),
    .m_axi_gmem1_0_ARSIZE(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_ARSIZE),
    .m_axi_gmem1_0_ARBURST(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_ARBURST),
    .m_axi_gmem1_0_ARLOCK(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_ARLOCK),
    .m_axi_gmem1_0_ARCACHE(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_ARCACHE),
    .m_axi_gmem1_0_ARPROT(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_ARPROT),
    .m_axi_gmem1_0_ARQOS(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_ARQOS),
    .m_axi_gmem1_0_ARREGION(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_ARREGION),
    .m_axi_gmem1_0_ARUSER(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_ARUSER),
    .m_axi_gmem1_0_RVALID(1'b0),
    .m_axi_gmem1_0_RREADY(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_RREADY),
    .m_axi_gmem1_0_RDATA(128'd0),
    .m_axi_gmem1_0_RLAST(1'b0),
    .m_axi_gmem1_0_RID(1'd0),
    .m_axi_gmem1_0_RFIFONUM(9'd0),
    .m_axi_gmem1_0_RUSER(1'd0),
    .m_axi_gmem1_0_RRESP(2'd0),
    .m_axi_gmem1_0_BVALID(gmem1_0_BVALID),
    .m_axi_gmem1_0_BREADY(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_BREADY),
    .m_axi_gmem1_0_BRESP(2'd0),
    .m_axi_gmem1_0_BID(1'd0),
    .m_axi_gmem1_0_BUSER(1'd0),
    .size(size_read_reg_266),
    .num_transfers(num_transfers_reg_276),
    .sext_ln38(trunc_ln1_reg_281),
    .sext_ln38_2(trunc_ln38_1_reg_292),
    .scalar(scalar_read_reg_271)
);

vector_scalar_sum_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .input_vector(input_vector),
    .output_vector(output_vector),
    .scalar(scalar),
    .size(size),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

vector_scalar_sum_gmem0_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM0_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM0_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM0_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM0_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM0_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM0_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM0_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM0_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM0_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM0_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM0_CACHE_VALUE ),
    .CH0_NUM_READ_OUTSTANDING( 16 ),
    .CH0_NUM_WRITE_OUTSTANDING( 16 ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 128 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
gmem0_m_axi_U(
    .AWVALID(m_axi_gmem0_AWVALID),
    .AWREADY(m_axi_gmem0_AWREADY),
    .AWADDR(m_axi_gmem0_AWADDR),
    .AWID(m_axi_gmem0_AWID),
    .AWLEN(m_axi_gmem0_AWLEN),
    .AWSIZE(m_axi_gmem0_AWSIZE),
    .AWBURST(m_axi_gmem0_AWBURST),
    .AWLOCK(m_axi_gmem0_AWLOCK),
    .AWCACHE(m_axi_gmem0_AWCACHE),
    .AWPROT(m_axi_gmem0_AWPROT),
    .AWQOS(m_axi_gmem0_AWQOS),
    .AWREGION(m_axi_gmem0_AWREGION),
    .AWUSER(m_axi_gmem0_AWUSER),
    .WVALID(m_axi_gmem0_WVALID),
    .WREADY(m_axi_gmem0_WREADY),
    .WDATA(m_axi_gmem0_WDATA),
    .WSTRB(m_axi_gmem0_WSTRB),
    .WLAST(m_axi_gmem0_WLAST),
    .WID(m_axi_gmem0_WID),
    .WUSER(m_axi_gmem0_WUSER),
    .ARVALID(m_axi_gmem0_ARVALID),
    .ARREADY(m_axi_gmem0_ARREADY),
    .ARADDR(m_axi_gmem0_ARADDR),
    .ARID(m_axi_gmem0_ARID),
    .ARLEN(m_axi_gmem0_ARLEN),
    .ARSIZE(m_axi_gmem0_ARSIZE),
    .ARBURST(m_axi_gmem0_ARBURST),
    .ARLOCK(m_axi_gmem0_ARLOCK),
    .ARCACHE(m_axi_gmem0_ARCACHE),
    .ARPROT(m_axi_gmem0_ARPROT),
    .ARQOS(m_axi_gmem0_ARQOS),
    .ARREGION(m_axi_gmem0_ARREGION),
    .ARUSER(m_axi_gmem0_ARUSER),
    .RVALID(m_axi_gmem0_RVALID),
    .RREADY(m_axi_gmem0_RREADY),
    .RDATA(m_axi_gmem0_RDATA),
    .RLAST(m_axi_gmem0_RLAST),
    .RID(m_axi_gmem0_RID),
    .RUSER(m_axi_gmem0_RUSER),
    .RRESP(m_axi_gmem0_RRESP),
    .BVALID(m_axi_gmem0_BVALID),
    .BREADY(m_axi_gmem0_BREADY),
    .BRESP(m_axi_gmem0_BRESP),
    .BID(m_axi_gmem0_BID),
    .BUSER(m_axi_gmem0_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(gmem0_0_ARVALID),
    .I_CH0_ARREADY(gmem0_0_ARREADY),
    .I_CH0_ARADDR(gmem0_0_ARADDR),
    .I_CH0_ARLEN(gmem0_0_ARLEN),
    .I_CH0_RVALID(gmem0_0_RVALID),
    .I_CH0_RREADY(gmem0_0_RREADY),
    .I_CH0_RDATA(gmem0_0_RDATA),
    .I_CH0_RFIFONUM(gmem0_0_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(gmem0_0_AWREADY),
    .I_CH0_AWADDR(64'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(gmem0_0_WREADY),
    .I_CH0_WDATA(128'd0),
    .I_CH0_WSTRB(16'd0),
    .I_CH0_BVALID(gmem0_0_BVALID),
    .I_CH0_BREADY(1'b0)
);

vector_scalar_sum_gmem1_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 4 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM1_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM1_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM1_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM1_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM1_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM1_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM1_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM1_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM1_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM1_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM1_CACHE_VALUE ),
    .CH0_NUM_READ_OUTSTANDING( 16 ),
    .CH0_NUM_WRITE_OUTSTANDING( 16 ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 128 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 0 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem1_m_axi_U(
    .AWVALID(m_axi_gmem1_AWVALID),
    .AWREADY(m_axi_gmem1_AWREADY),
    .AWADDR(m_axi_gmem1_AWADDR),
    .AWID(m_axi_gmem1_AWID),
    .AWLEN(m_axi_gmem1_AWLEN),
    .AWSIZE(m_axi_gmem1_AWSIZE),
    .AWBURST(m_axi_gmem1_AWBURST),
    .AWLOCK(m_axi_gmem1_AWLOCK),
    .AWCACHE(m_axi_gmem1_AWCACHE),
    .AWPROT(m_axi_gmem1_AWPROT),
    .AWQOS(m_axi_gmem1_AWQOS),
    .AWREGION(m_axi_gmem1_AWREGION),
    .AWUSER(m_axi_gmem1_AWUSER),
    .WVALID(m_axi_gmem1_WVALID),
    .WREADY(m_axi_gmem1_WREADY),
    .WDATA(m_axi_gmem1_WDATA),
    .WSTRB(m_axi_gmem1_WSTRB),
    .WLAST(m_axi_gmem1_WLAST),
    .WID(m_axi_gmem1_WID),
    .WUSER(m_axi_gmem1_WUSER),
    .ARVALID(m_axi_gmem1_ARVALID),
    .ARREADY(m_axi_gmem1_ARREADY),
    .ARADDR(m_axi_gmem1_ARADDR),
    .ARID(m_axi_gmem1_ARID),
    .ARLEN(m_axi_gmem1_ARLEN),
    .ARSIZE(m_axi_gmem1_ARSIZE),
    .ARBURST(m_axi_gmem1_ARBURST),
    .ARLOCK(m_axi_gmem1_ARLOCK),
    .ARCACHE(m_axi_gmem1_ARCACHE),
    .ARPROT(m_axi_gmem1_ARPROT),
    .ARQOS(m_axi_gmem1_ARQOS),
    .ARREGION(m_axi_gmem1_ARREGION),
    .ARUSER(m_axi_gmem1_ARUSER),
    .RVALID(m_axi_gmem1_RVALID),
    .RREADY(m_axi_gmem1_RREADY),
    .RDATA(m_axi_gmem1_RDATA),
    .RLAST(m_axi_gmem1_RLAST),
    .RID(m_axi_gmem1_RID),
    .RUSER(m_axi_gmem1_RUSER),
    .RRESP(m_axi_gmem1_RRESP),
    .BVALID(m_axi_gmem1_BVALID),
    .BREADY(m_axi_gmem1_BREADY),
    .BRESP(m_axi_gmem1_BRESP),
    .BID(m_axi_gmem1_BID),
    .BUSER(m_axi_gmem1_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(1'b0),
    .I_CH0_ARREADY(gmem1_0_ARREADY),
    .I_CH0_ARADDR(64'd0),
    .I_CH0_ARLEN(32'd0),
    .I_CH0_RVALID(gmem1_0_RVALID),
    .I_CH0_RREADY(1'b0),
    .I_CH0_RDATA(gmem1_0_RDATA),
    .I_CH0_RFIFONUM(gmem1_0_RFIFONUM),
    .I_CH0_AWVALID(gmem1_0_AWVALID),
    .I_CH0_AWREADY(gmem1_0_AWREADY),
    .I_CH0_AWADDR(gmem1_0_AWADDR),
    .I_CH0_AWLEN(gmem1_0_AWLEN),
    .I_CH0_WVALID(gmem1_0_WVALID),
    .I_CH0_WREADY(gmem1_0_WREADY),
    .I_CH0_WDATA(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_WDATA),
    .I_CH0_WSTRB(grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_WSTRB),
    .I_CH0_BVALID(gmem1_0_BVALID),
    .I_CH0_BREADY(gmem1_0_BREADY)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_ap_start_reg <= 1'b1;
        end else if ((grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_ap_ready == 1'b1)) begin
            grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        empty_reg_287 <= empty_fu_220_p3;
        num_transfers_reg_276 <= num_transfers_fu_196_p3;
        scalar_read_reg_271 <= scalar;
        size_read_reg_266 <= size;
        trunc_ln1_reg_281 <= {{input_vector[63:4]}};
        trunc_ln38_1_reg_292 <= {{output_vector[63:4]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        zext_ln38_reg_303[31 : 0] <= zext_ln38_fu_251_p1[31 : 0];
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_ap_done == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

always @ (*) begin
    if ((gmem1_0_BVALID == 1'b0)) begin
        ap_ST_fsm_state16_blk = 1'b1;
    end else begin
        ap_ST_fsm_state16_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem0_0_ARREADY == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((gmem1_0_AWREADY == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((gmem1_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((gmem1_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((gmem0_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        gmem0_0_ARADDR = sext_ln38_fu_238_p1;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem0_0_ARADDR = grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_ARADDR;
    end else begin
        gmem0_0_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((gmem0_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        gmem0_0_ARLEN = zext_ln38_fu_251_p1;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem0_0_ARLEN = grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_ARLEN;
    end else begin
        gmem0_0_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((gmem0_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        gmem0_0_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem0_0_ARVALID = grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_ARVALID;
    end else begin
        gmem0_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem0_0_RREADY = grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem0_0_RREADY;
    end else begin
        gmem0_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        gmem0_blk_n_AR = m_axi_gmem0_ARREADY;
    end else begin
        gmem0_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((gmem1_0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        gmem1_0_AWADDR = sext_ln38_2_fu_256_p1;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem1_0_AWADDR = grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_AWADDR;
    end else begin
        gmem1_0_AWADDR = 'bx;
    end
end

always @ (*) begin
    if (((gmem1_0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        gmem1_0_AWLEN = zext_ln38_reg_303;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem1_0_AWLEN = grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_AWLEN;
    end else begin
        gmem1_0_AWLEN = 'bx;
    end
end

always @ (*) begin
    if (((gmem1_0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        gmem1_0_AWVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem1_0_AWVALID = grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_AWVALID;
    end else begin
        gmem1_0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((gmem1_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
        gmem1_0_BREADY = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem1_0_BREADY = grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_BREADY;
    end else begin
        gmem1_0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem1_0_WVALID = grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_m_axi_gmem1_0_WVALID;
    end else begin
        gmem1_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        gmem1_blk_n_AW = m_axi_gmem1_AWREADY;
    end else begin
        gmem1_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        gmem1_blk_n_B = m_axi_gmem1_BVALID;
    end else begin
        gmem1_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((gmem0_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((gmem1_0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((1'b1 == ap_CS_fsm_state11) & (grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            if (((gmem1_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln35_fu_142_p2 = (size + 32'd3);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign empty_fu_220_p3 = ((icmp_ln38_fu_204_p2[0:0] == 1'b1) ? num_transfers_fu_196_p3 : 31'd0);

assign grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_ap_start = grp_vector_scalar_sum_Pipeline_PROCESS_LOOP_fu_129_ap_start_reg;

assign icmp_ln38_fu_204_p2 = (($signed(size) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign num_transfers_fu_196_p3 = ((tmp_2_fu_148_p3[0:0] == 1'b1) ? sub_ln35_1_fu_176_p2 : zext_ln35_1_fu_192_p1);

assign sext_ln38_1_fu_248_p1 = $signed(empty_reg_287);

assign sext_ln38_2_fu_256_p1 = $signed(trunc_ln38_1_reg_292);

assign sext_ln38_fu_238_p1 = $signed(trunc_ln1_reg_281);

assign sub_ln35_1_fu_176_p2 = (31'd0 - zext_ln35_fu_172_p1);

assign sub_ln35_fu_156_p2 = ($signed(32'd4294967293) - $signed(size));

assign tmp_1_fu_182_p4 = {{add_ln35_fu_142_p2[31:2]}};

assign tmp_2_fu_148_p3 = add_ln35_fu_142_p2[32'd31];

assign tmp_fu_162_p4 = {{sub_ln35_fu_156_p2[31:2]}};

assign zext_ln35_1_fu_192_p1 = tmp_1_fu_182_p4;

assign zext_ln35_fu_172_p1 = tmp_fu_162_p4;

assign zext_ln38_fu_251_p1 = $unsigned(sext_ln38_1_fu_248_p1);

always @ (posedge ap_clk) begin
    zext_ln38_reg_303[63:32] <= 32'b00000000000000000000000000000000;
end

endmodule //vector_scalar_sum
